
app = "momentor-room"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
PORT = "3000"

[build]
  builtin = "node"

[experimental]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 3000
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
